steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_BUILD_DISTRO$_DISTRO_VERSION.waveform-resource', 'ci/$_BUILD_DISTRO/$_DISTRO_VERSION' ]

images:
- 'gcr.io/$PROJECT_ID/$_BUILD_DISTRO$_DISTRO_VERSION.waveform-resource'

timeout: 10m
